import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTaskChecklistTimestampsTable1772867331545 implements MigrationInterface {
    name = 'CreateTaskChecklistTimestampsTable1772867331545'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_checklist" DROP CONSTRAINT "FK_task_checklist_task"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_tasks_assigned_to"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_tasks_assigned_by"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_tasks_project"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_tasks_task_type"`);
        await queryRunner.query(`ALTER TABLE "task_types" DROP CONSTRAINT "FK_task_types_department"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_departments_project_type"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_clients_sales_manager"`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" DROP CONSTRAINT "FK_employee_profiles_users"`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" DROP CONSTRAINT "FK_employee_profiles_departments"`);
        await queryRunner.query(`ALTER TABLE "project_documents" DROP CONSTRAINT "FK_project_documents_project"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_project_type"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_project_manager"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_project_lead"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_project_creator"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_project_client"`);
        await queryRunner.query(`ALTER TABLE "admin_profiles" DROP CONSTRAINT "FK_admin_profiles_users"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_roles"`);
        await queryRunner.query(`ALTER TABLE "task_activity" DROP CONSTRAINT "FK_task_activity_task"`);
        await queryRunner.query(`ALTER TABLE "task_activity" DROP CONSTRAINT "FK_task_activity_changed_by"`);
        await queryRunner.query(`ALTER TABLE "task_files" DROP CONSTRAINT "FK_task_files_task"`);
        await queryRunner.query(`ALTER TABLE "task_files" DROP CONSTRAINT "FK_task_files_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "FK_project_team_project"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "FK_project_team_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_departments_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`CREATE TABLE "task_checklist_timestamps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "hours" integer NOT NULL, "minutes" integer NOT NULL, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "checklist_id" uuid, CONSTRAINT "PK_8c5f17f2e19b1599afa56637856" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "task_checklist" DROP COLUMN "item_name"`);
        await queryRunner.query(`ALTER TABLE "task_checklist" ADD "item_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."task_type_status_enum" RENAME TO "task_type_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."task_types_status_enum" AS ENUM('Active', 'Inactive')`);
        await queryRunner.query(`ALTER TABLE "task_types" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "task_types" ALTER COLUMN "status" TYPE "public"."task_types_status_enum" USING "status"::"text"::"public"."task_types_status_enum"`);
        await queryRunner.query(`ALTER TABLE "task_types" ALTER COLUMN "status" SET DEFAULT 'Active'`);
        await queryRunner.query(`DROP TYPE "public"."task_type_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "contacts"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "contacts" json`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91fddbe23e927e1e525c152baa" ON "departments" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1a8ad2f15c8b55e6f6ab70260" ON "project_team_members" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c41b3dac8b965ba9b8747e565c" ON "project_team_members" ("employee_id") `);
        await queryRunner.query(`ALTER TABLE "task_checklist_timestamps" ADD CONSTRAINT "FK_aa65b94b1011abab11fb5899e30" FOREIGN KEY ("checklist_id") REFERENCES "task_checklist"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_checklist" ADD CONSTRAINT "FK_8b3e936379a32495314fdc6721e" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9430f12c5a1604833f64595a57f" FOREIGN KEY ("assigned_to_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_3e08a7ca125a175cf899b09f71a" FOREIGN KEY ("assigned_by_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_ea76a982cfc3dd4bff34daaf036" FOREIGN KEY ("task_type_id") REFERENCES "task_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_types" ADD CONSTRAINT "FK_7dfbb6bf897d5a0ad1c12b3bfb8" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_f5e00cebb41d0ec9199b0825f87" FOREIGN KEY ("project_type_id") REFERENCES "project_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_f108a8c46926558ba45cee75aff" FOREIGN KEY ("sales_manager_id") REFERENCES "employee_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ADD CONSTRAINT "FK_986e309c16f09ce6cc47d674cfe" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ADD CONSTRAINT "FK_460fcd97e0cdf808147c3d03721" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_documents" ADD CONSTRAINT "FK_ce91a721e078a2d9852b61ad8f2" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_e8cea670941d4e9fa835394314b" FOREIGN KEY ("project_type_id") REFERENCES "project_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_aaf9d96cf264ced3a4828873132" FOREIGN KEY ("project_manager_id") REFERENCES "admin_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_b1bc2a5f9df8b23eed42db3911c" FOREIGN KEY ("project_lead_id") REFERENCES "employee_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "admin_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_ca29f959102228649e714827478" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_profiles" ADD CONSTRAINT "FK_a3d9676173d45095f26252902b1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_activity" ADD CONSTRAINT "FK_7de35d88c452b75c02120595521" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_activity" ADD CONSTRAINT "FK_c9f52b1ea325a7ee7b28de4e48f" FOREIGN KEY ("changed_by_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_files" ADD CONSTRAINT "FK_e302f4010ff50a1e8199a489090" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_files" ADD CONSTRAINT "FK_347bda3b14237c75639b377a67f" FOREIGN KEY ("uploaded_by_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "FK_c1a8ad2f15c8b55e6f6ab702604" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "FK_c41b3dac8b965ba9b8747e565c3" FOREIGN KEY ("employee_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "FK_c41b3dac8b965ba9b8747e565c3"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "FK_c1a8ad2f15c8b55e6f6ab702604"`);
        await queryRunner.query(`ALTER TABLE "task_files" DROP CONSTRAINT "FK_347bda3b14237c75639b377a67f"`);
        await queryRunner.query(`ALTER TABLE "task_files" DROP CONSTRAINT "FK_e302f4010ff50a1e8199a489090"`);
        await queryRunner.query(`ALTER TABLE "task_activity" DROP CONSTRAINT "FK_c9f52b1ea325a7ee7b28de4e48f"`);
        await queryRunner.query(`ALTER TABLE "task_activity" DROP CONSTRAINT "FK_7de35d88c452b75c02120595521"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "admin_profiles" DROP CONSTRAINT "FK_a3d9676173d45095f26252902b1"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_ca29f959102228649e714827478"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_b1bc2a5f9df8b23eed42db3911c"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_aaf9d96cf264ced3a4828873132"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_e8cea670941d4e9fa835394314b"`);
        await queryRunner.query(`ALTER TABLE "project_documents" DROP CONSTRAINT "FK_ce91a721e078a2d9852b61ad8f2"`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" DROP CONSTRAINT "FK_460fcd97e0cdf808147c3d03721"`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" DROP CONSTRAINT "FK_986e309c16f09ce6cc47d674cfe"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_f108a8c46926558ba45cee75aff"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_f5e00cebb41d0ec9199b0825f87"`);
        await queryRunner.query(`ALTER TABLE "task_types" DROP CONSTRAINT "FK_7dfbb6bf897d5a0ad1c12b3bfb8"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_ea76a982cfc3dd4bff34daaf036"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_3e08a7ca125a175cf899b09f71a"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9430f12c5a1604833f64595a57f"`);
        await queryRunner.query(`ALTER TABLE "task_checklist" DROP CONSTRAINT "FK_8b3e936379a32495314fdc6721e"`);
        await queryRunner.query(`ALTER TABLE "task_checklist_timestamps" DROP CONSTRAINT "FK_aa65b94b1011abab11fb5899e30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c41b3dac8b965ba9b8747e565c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1a8ad2f15c8b55e6f6ab70260"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91fddbe23e927e1e525c152baa"`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "contacts"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "contacts" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."task_type_status_enum_old" AS ENUM('Active', 'Inactive')`);
        await queryRunner.query(`ALTER TABLE "task_types" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "task_types" ALTER COLUMN "status" TYPE "public"."task_type_status_enum_old" USING "status"::"text"::"public"."task_type_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "task_types" ALTER COLUMN "status" SET DEFAULT 'Active'`);
        await queryRunner.query(`DROP TYPE "public"."task_types_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_type_status_enum_old" RENAME TO "task_type_status_enum"`);
        await queryRunner.query(`ALTER TABLE "task_checklist" DROP COLUMN "item_name"`);
        await queryRunner.query(`ALTER TABLE "task_checklist" ADD "item_name" character varying(255) NOT NULL`);
        await queryRunner.query(`DROP TABLE "task_checklist_timestamps"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_departments_code" ON "departments" ("code") WHERE (code IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "FK_project_team_employee" FOREIGN KEY ("employee_id") REFERENCES "employee_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "FK_project_team_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_files" ADD CONSTRAINT "FK_task_files_uploaded_by" FOREIGN KEY ("uploaded_by_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_files" ADD CONSTRAINT "FK_task_files_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_activity" ADD CONSTRAINT "FK_task_activity_changed_by" FOREIGN KEY ("changed_by_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_activity" ADD CONSTRAINT "FK_task_activity_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_roles" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_profiles" ADD CONSTRAINT "FK_admin_profiles_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_project_client" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_project_creator" FOREIGN KEY ("created_by") REFERENCES "admin_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_project_lead" FOREIGN KEY ("project_lead_id") REFERENCES "employee_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_project_manager" FOREIGN KEY ("project_manager_id") REFERENCES "admin_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_project_type" FOREIGN KEY ("project_type_id") REFERENCES "project_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_documents" ADD CONSTRAINT "FK_project_documents_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ADD CONSTRAINT "FK_employee_profiles_departments" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ADD CONSTRAINT "FK_employee_profiles_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_clients_sales_manager" FOREIGN KEY ("sales_manager_id") REFERENCES "employee_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_departments_project_type" FOREIGN KEY ("project_type_id") REFERENCES "project_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_types" ADD CONSTRAINT "FK_task_types_department" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_tasks_task_type" FOREIGN KEY ("task_type_id") REFERENCES "task_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_tasks_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_tasks_assigned_by" FOREIGN KEY ("assigned_by_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_tasks_assigned_to" FOREIGN KEY ("assigned_to_id") REFERENCES "employee_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_checklist" ADD CONSTRAINT "FK_task_checklist_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
